// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ61jKCoPKnclxH8bMn6J-q6L1gSu7C_s',
    appId: '1:184959061243:web:3791e720f914ead760345e',
    messagingSenderId: '184959061243',
    projectId: 'h4-scrumboard-827ed',
    authDomain: 'h4-scrumboard-827ed.firebaseapp.com',
    databaseURL: 'https://h4-scrumboard-827ed-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'h4-scrumboard-827ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKnqJfLN97d9a8hUDNGzYYGLuPXtpbNQ0',
    appId: '1:184959061243:android:d5e31f6dae539ab960345e',
    messagingSenderId: '184959061243',
    projectId: 'h4-scrumboard-827ed',
    databaseURL: 'https://h4-scrumboard-827ed-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'h4-scrumboard-827ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtXpOzi0YxjoEJkLW8Odl10vuBd-YMDfs',
    appId: '1:184959061243:ios:facf68bc7057f81f60345e',
    messagingSenderId: '184959061243',
    projectId: 'h4-scrumboard-827ed',
    databaseURL: 'https://h4-scrumboard-827ed-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'h4-scrumboard-827ed.appspot.com',
    iosClientId: '184959061243-o0mkqoqobhm6080uu35n6frq7r1p67r6.apps.googleusercontent.com',
    iosBundleId: 'com.example.scrumboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtXpOzi0YxjoEJkLW8Odl10vuBd-YMDfs',
    appId: '1:184959061243:ios:facf68bc7057f81f60345e',
    messagingSenderId: '184959061243',
    projectId: 'h4-scrumboard-827ed',
    databaseURL: 'https://h4-scrumboard-827ed-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'h4-scrumboard-827ed.appspot.com',
    iosClientId: '184959061243-o0mkqoqobhm6080uu35n6frq7r1p67r6.apps.googleusercontent.com',
    iosBundleId: 'com.example.scrumboard',
  );
}
